{{- $ns := .Values.namespace -}}
{{- $tag := .Values.imageTag -}}
{{- $secret := .Values.imagePullSecret -}}
{{- $replicas := .Values.replicaCount -}}
{{- $pgPass := .Values.postgres.password -}}
{{- $kafka := .Values.kafka.bootstrapServers -}}
{{- $registry := .Values.imageRegistry -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: {{ $ns }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      imagePullSecrets: [{name: {{ $secret }}}]
      containers:
        - name: eureka-server
          image: {{ printf "%s/eureka-server:%s" $registry $tag }}
          ports: [{containerPort: 8761}]
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: eureka-server
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: {{ $ns }}
spec:
  selector: {app: eureka-server}
  ports: [{port: 8761}]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: {{ $ns }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels: {app: gateway-service}
  template:
    metadata:
      labels: {app: gateway-service}
    spec:
      imagePullSecrets: [{name: {{ $secret }}}]
      containers:
        - name: gateway-service
          image: {{ printf "%s/gateway-service:%s" $registry $tag }}
          ports: [{containerPort: 8084}]
          env:
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ $ns }}
spec:
  selector: {app: gateway-service}
  ports: [{port: 8084}]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ $ns }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels: {app: auth-service}
  template:
    metadata:
      labels: {app: auth-service}
    spec:
      imagePullSecrets: [{name: {{ $secret }}}]
      containers:
        - name: auth-service
          image: {{ printf "%s/auth-service:%s" $registry $tag }}
          ports: [{containerPort: 8080}]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://auth-db:5432/{{ .Values.services.auth.dbName }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.services.auth.dbUser }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ $pgPass }}"
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ $ns }}
spec:
  selector: {app: auth-service}
  ports: [{port: 8080}]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: {{ $ns }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels: {app: events-service}
  template:
    metadata:
      labels: {app: events-service}
    spec:
      imagePullSecrets: [{name: {{ $secret }}}]
      containers:
        - name: events-service
          image: {{ printf "%s/events-service:%s" $registry $tag }}
          ports: [{containerPort: 8080}]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://events-db:5432/{{ .Values.services.events.dbName }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.services.events.dbUser }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ $pgPass }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ $kafka }}
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: {{ $ns }}
spec:
  selector: {app: events-service}
  ports: [{port: 8080}]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: {{ $ns }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels: {app: notifications-service}
  template:
    metadata:
      labels: {app: notifications-service}
    spec:
      imagePullSecrets: [{name: {{ $secret }}}]
      containers:
        - name: notifications-service
          image: {{ printf "%s/notifications-service:%s" $registry $tag }}
          ports: [{containerPort: 8080}]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://notifications-db:5432/{{ .Values.services.notifications.dbName }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.services.notifications.dbUser }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ $pgPass }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ $kafka }}
            - name: KAFKA_ORDERS_TOPIC
              value: {{ .Values.services.notifications.topics.orders }}
            - name: KAFKA_PAYMENTS_TOPIC
              value: {{ .Values.services.notifications.topics.payments }}
            - name: KAFKA_EVENTS_TOPIC
              value: {{ .Values.services.notifications.topics.events }}
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: {{ $ns }}
spec:
  selector: {app: notifications-service}
  ports: [{port: 8080}]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: {{ $ns }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels: {app: orders-service}
  template:
    metadata:
      labels: {app: orders-service}
    spec:
      imagePullSecrets: [{name: {{ $secret }}}]
      containers:
        - name: orders-service
          image: {{ printf "%s/orders-service:%s" $registry $tag }}
          ports: [{containerPort: 8080}]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://orders-db:5432/{{ .Values.services.orders.dbName }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.services.orders.dbUser }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ $pgPass }}"
            - name: EVENTS_SERVICE_BASE_URL
              value: http://events-service:8080
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ $kafka }}
            - name: KAFKA_ORDERS_TOPIC
              value: {{ .Values.services.orders.topics.orders }}
            - name: KAFKA_PAYMENTS_TOPIC
              value: {{ .Values.services.orders.topics.payments }}
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: {{ $ns }}
spec:
  selector: {app: orders-service}
  ports: [{port: 8080}]
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: {{ $ns }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels: {app: payment-service}
  template:
    metadata:
      labels: {app: payment-service}
    spec:
      imagePullSecrets: [{name: {{ $secret }}}]
      containers:
        - name: payment-service
          image: {{ printf "%s/payment-service:%s" $registry $tag }}
          ports: [{containerPort: 8080}]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://payment-db:5432/{{ .Values.services.payment.dbName }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.services.payment.dbUser }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ $pgPass }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ $kafka }}
            - name: KAFKA_ORDERS_TOPIC
              value: {{ .Values.services.payment.topics.orders }}
            - name: KAFKA_PAYMENTS_TOPIC
              value: {{ .Values.services.payment.topics.payments }}
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: {{ $ns }}
spec:
  selector: {app: payment-service}
  ports: [{port: 8080}]