{{- $ns := .Values.namespace -}}
{{- $pgPass := .Values.postgres.password -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ $ns }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ $ns }}
spec:
  selector:
    app: redis
  ports:
    - port: {{ .Values.redis.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: {{ $ns }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: {{ $ns }}
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ $ns }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-svc:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: {{ $ns }}
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
---
{{- range $key, $val := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $key }}-db
  namespace: {{ $ns }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $key }}-db
  template:
    metadata:
      labels:
        app: {{ $key }}-db
    spec:
      containers:
        - name: postgres
          image: {{ $.Values.postgres.image }}
          env:
            - name: POSTGRES_DB
              value: {{ $val.dbName }}
            - name: POSTGRES_USER
              value: {{ $val.dbUser }}
            - name: POSTGRES_PASSWORD
              value: "{{ $pgPass }}"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}-db
  namespace: {{ $ns }}
spec:
  selector:
    app: {{ $key }}-db
  ports:
    - port: 5432
---
{{- end }}