{{- if .Values.registry.username -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}}}" (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc }}
{{- end -}}